### ISSUE TITLE
Question - Why not use JSON for the API?

### ISSUE THREAD

**Issue by osirisr** [steemit/devportal#18]
So from the documentation, it seems we have to make an HTML file and call a JS file to query that HTML page and send post data that way. This is incredibly strange to me. Is this kind of practice common? Why not just use standard JSON calls and endpoints like every other API? Does the fact that the API is based on blockchain make this difficult?

**Comment by theapplicationist** [comment]
Which part of the documentation are you referring to? I think the JS examples. The JS API examples are using a HTML page as an example but it doesn't necessarily mean you have to do that. It states in the docs "For simplicity, this is done with a single HTML file and inline javascript."

**Comment by TimCliff** [comment]
What you are looking for will most likely be covered in https://github.com/steemit/devportal/issues/37

**Comment by relativityboy** [comment]
@osirisr. There's no need to make an html file. The examples do, and will, at the start assume a simple level of developer understanding, so that those who are less skilled will still be able to craft requests and work with Steem.

If your understanding of js/node/https is good enough it's trivial to use steem-js to call from a node.js process, or if you're familiar with HTTP posts to craft your own based on analysis of the steem-js library (or the currently 3rd party dsteem library).

The specifics fields of many api calls will be covered once #37 is complete. And that issue actually references a blog post that has the properties many of Steem, and Steemit's api calls.
