### ISSUE TITLE
Tutorial: Meta: List new tutorials needed after HF20

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#338]
As of HF20, Steem has new capabilities. As a developer I want to know what they are and how to use them *so I can successfully & effectively participate on Steem*

**AC**
- [x] In `# Results` a list of tutorials, with at least one sentence explaining what each is intended to teach (no boilerplate sentences)

**Comment by relativityboy** [comment]
Recipe: Claim and account / create an account

**Comment by roboza** [comment]
# Results

1. Unlimited content editing
Steemit.com now allows editing of posts older than 7 days (archived). An update to the tutorial #12_edit_content_patching which mention the restriction is required.

2. Resource credits.
The manner in which RC is assigned and the amount of RC used by various transactions on the blockchain has been changed significantly. This changes the amount of posts, votes, transfers etc. that can be done within the regeneration period. A possible write-up could be considered to make developers aware of this or a recipe on how to track and calculate the costs.

3. Account creation
New accounts can now be created by way of an account creation token instead the normal 3 STEEM cost. Instead of giving new accounts STEEM power, the account fee would be destroyed and removed from the token supply. A minimum bandwidth assigned to new accounts that would allow new users to perform actions on the blockchain without the requirement of STEEM power. Changes to the current tutorials would have to include the new method or mention of them in the readme. With new creation processes there might be a need to create a new recipe with in-depth explanation of the new claim_account_operation and create_claimed_account_operation due to account_create_with_delegation_operation being deprecated.

4. Delegated VESTS.
Tutorial #27_delegate_power readme needs to be updated as the expiring delegations period has been reduced from 7 days to 5 days

5. Power Down
Power down restrictions have been removed (The rule that stopped new accounts from powering down immediately). This should be investigated and the tutorials updated with the new restrictions or lack thereof.(possibly included in account creation recipe)

6. Comment limit
Tutorial #11_submit_comment_reply should include note that comments can now be made every 3 seconds (every block)

**Comment by relativityboy** [comment]
LGTM

**Comment by relativityboy** [comment]
I kinda feel like we can skip 5.
