### ISSUE TITLE
JS Tutorials - Dev Environment Description

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#36]
Our tutorials need to level set expectations for the developer's environment. We could call it "application environment guidelines" or some such. It should go at the top of the tutorials section, and be hash linkable.

Use results from #39 

**AC**
- [x] Describe base skill level expected of a developer. (Links to resources for acquiring those skills)
- [x] Establish a base environment that will work in node 8+ and supports the newest version of ES. Observations and final environment description should be in comments on this issue.
- [x] Add English language description of the environment (Environment Description), include links to appropriate 3rd party resources & tutorials so a JS developer with little experience can bootstrap themselves.
- [x] Environment Description should be deep linkable.
- [x] Environment Description should be at the top of the tutorials section after the greeting and/or on the intro page of the tutorials section if the section has multiple pages.

**Comment by feruzm** [comment]
* General
Medium understanding of HTML (DOM), CSS and Javascript is required, since most developers already familiar with additional Javascript frameworks (React, Angular, Vue, etc.), so they should be familiar enough with [ES6](http://ccoenraets.github.io/es6-tutorial/) to understand, and act on a tutorial written in [ES6](http://ccoenraets.github.io/es6-tutorial/) without additional explanation and how [DOM](https://www.w3.org/TR/WD-DOM/introduction.html) works.

* Server side
Developer should be very familiar with [Nodejs 8+](https://nodejs.org/en/docs/guides/getting-started-guide/) and package management, and usage of simple packages like express, files system, require, import and ES6/harmony style coding structure. When/If we will have tutorials for backend setup, dev should be familiar enough to follow common practices for mentioned packages.

* Client side
By now all major browsers support ES6, so developer should be familiar with terms/features like template literals, destructuring assignment, object literals, arrow functions, promises, block-scoped variables, modules, etc. As for webpack or browserify or babel mentioned in standups, I think, it might not be necessary for simple tutorials. [VanillaJS](http://vanilla-js.com/) with ES6 should be sufficient in my opinion and any dev who knows js can turn code/tutorials to their favorite js framework, if necessary.
