### ISSUE TITLE
Determine JS Tutorial Environments & Dev Skills

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#39]
We want to have a clear set of expectations when writing Javascript tutorials for developers. We want to define how good they must be, so that we don't over-explain. We want to define what tools they have available if they're writing a Node.js app, and what tools if they're writing a Client-side only app.
If they're writing an app using both client & server side code, the tools should be a union of the Client/Server sets.

Notes and debate can/should be taken on this issue. 
Use current best practice.
No minimum use of 3rd party codebases, NO heavy UI frameworks, except vanillaJS which is permitted (see http://vanilla-js.com/)

**AC**
- [x] Define the minimum skillset we expect a Javascript developer to have
- [x] Define the Javascript Development environment we expect for Server side development.
- [x] Define the Javascript Development environment we expect for Client side development.
- [x] The above are defined in a single comment on this issue. And be labeled **Conclusion**

**Comment by feruzm** [comment]
Discussion notes, please give your feedbacks or suggestions, @relativityboy, @roboza...

* Define the minimum skillset we expect a Javascript developer to have

Medium understanding of HTML (DOM), CSS and Javascript is required, since most developers already familiar with additional Javascript frameworks (React, Angular, Vue, etc.), so they should be quite familiar with Javascript functions, objects and how DOM works.

* Define the Javascript Development environment we expect for Server side development.

Developer should be very familiar with Nodejs 8+ and package management, and usage of simple packages like express, files system, require, import and es6/harmony style coding structure. When/If we will have tutorials for backend setup, dev should be familiar enough to follow common practices for mentioned packages. 

* Define the Javascript Development environment we expect for Client side development.

By now all major browsers support ECMAScript 6, so developer should be familiar with terms/features like template literals, destructuring assignment, object literals, arrow functions, promises, block-scoped variables, modules, etc. As for webpack or browserify or babel mentioned in standups, I think, it might not be necessary for simple tutorials. VanillaJS with es6 should be sufficient in my opinion and any dev who knows js can turn code/tutorials to their favorite js framework, if necessary.

**Comment by relativityboy** [comment]
> should be quite familiar with Javascript functions
Maybe "they should be familiar enough with es6 to understand, and act on a tutorial written in es6 without additional explanation" ? 

Otherwise, the above looks good enough to me that we should be able to execute on it. @feruzm Can you endorse my suggestion?

**Comment by feruzm** [comment]
ok, I will wrap up these issues in few hours today. Thank you!
