### ISSUE TITLE
Add main nav item for appbase api docs

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#71]
The appbase api call and response definitions are already in the codebase. Make a menu item for them, and make sure they still work correctly

**AC**
- [x] main nav item exists for appbase api docs
- [x] api docs work on separate page in reasonable manner.

**Comment by roboza** [comment]
I have completed the integration into the main nav however the JSON and javascript is not formatting.

I need to complete #72 before we can get the formatting right. I am going to leave this in this state until issue #72 is complete and will then merge those changes into this so that we can have the correct formatting on board.

**Comment by inertia186** [comment]
Added css to fix format of json (4b81406a5914aa1cce4edc702b5d79b4d6d63f75), but we're still missing the plugin for adding whitespace.
